CREATE DATABASE LOJA_INFO;
USE LOJA_INFO;
CREATE TABLE CLIENTES(
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (100),
CADASTRO VARCHAR (20),
LAT DECIMAL (10,8),
LNG DECIMAL (11,8),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(50),
DATA_NASCIMENTO DATE
);
CREATE TABLE VENDAS(
ID_PRODUTO INT,
ID_CLIENTE INT,
DATA_VENDA DATE,
PRECO_VENDA DECIMAL (8,2),
QUANTIDADE INT
);
CREATE TABLE FUNCIONARIOS(
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY,
NOME  VARCHAR (100),
EMAIL VARCHAR (50),
TELEFONE VARCHAR (15),
DATA_NASCIMENTO DATE
);
CREATE TABLE ESTOQUE(
ID_PRODUTO INT,
QUANTIDADE INT
);
CREATE TABLE PRODUTOS(
ID_PRODUTOS INT AUTO_INCREMENT PRIMARY KEY,
MARCA VARCHAR (40),
PRECO_VENDA DECIMAL (8,2),
NOME VARCHAR (100),
MODELO VARCHAR (20)

);
CREATE TABLE COMPRA(
ID_PRODUTO INT,
ID_FORNECEDOR INT,
CUSTO DECIMAL (8,2),
PRECO_VENDA DECIMAL (8,2),
QUANTIDADE INT
);
CREATE TABLE FORNECEDOR(
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
CNPJ CHAR (14),
NOME VARCHAR (100),
LAT DECIMAL (10,8),
LNG DECIMAL (11,8),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(50)
);
CREATE TABLE PF (
ID_CLIENTE INT,
CPF CHAR (14)
);
CREATE TABLE PF (
ID_CLIENTE INT,
CNPJ CHAR (14)
);