CREATE DATABASE TAREFA_LEONCIO;
USE TAREFA_LEONCIO_NOS_ABANDONOU;
CREATE TABLE CLIENTES(
CPF VARCHAR (11),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR (50),
LIMITE_DE_CREDITO FLOAT,
VOLUME_DE_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT (1))